<?php


/**
 * Created by PhpStorm.
 * User: jim
 * Date: 2020-02-22
 * Time: 19:00
 */

class ApiController extends \Lwenjim\Yaf\Controller
{
    protected function indexAction()
    {
        parent::indexAction(); // TODO: Change the autogenerated stub
    }

}
